### ISSUE TITLE
attribution of ballet library

### ISSUE THREAD

**Issue by micahjsmith** [eleveyuan/pada#3]
hey @eleveyuan , seems like a cool library you are working on. I notice that it is substantially derived from github.com/ballet/ballet. I'm glad that you are inspired by our prior work and are free to reuse it given its permissive MIT licensing. That being said, would you please include an attribution to our work in your README? I'd really appreciate it, thank you!

something like:

```
# Credits

* This library derives from and extends Ballet, a lightweight framework for collaborative, open-source feature engineering (https://github.com/ballet/ballet)
```

also, I'm happy to take pull requests upstream! :)

**Comment by eleveyuan** [comment]
Sorry to reply you @micahjsmith late. Sure. I'll add it in my README. Thanks to your project.
